name: CustomItems
version: '${project.version}'
main: me.stephenminer.customitems.CustomItems
api-version: '1.20'
commands:
  itembuilder:
    description: base for all cmds in plugin
    permission: "itembuilder.cmds.builder"
  createitem:
    usage: /createItem [id] [material]
    permission: "itembuilder.commands.create"
  forceitems:
    usage: /forceitems
  reloaditem:
    permission: "itembuilder.cmds.reload"
  updateitem: